---
version: "3.2"
services:
  app81:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          PHP_VERSION: '8.1'
    environment:
      PHP_IDE_CONFIG: 'serverName=icanboogie-cldr-generator'
    volumes:
    - .:/app:delegated
    - ~/.composer:/root/.composer:delegated
    working_dir: /app
