#!/usr/bin/env php
<?php

namespace ICanBoogie\CLDR\Generator;

use ICanBoogie\CLDR\Cache\FileCache;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\CommandLoader\ContainerCommandLoader;

require_once __DIR__ . '/../vendor/autoload.php';

const CACHE = __DIR__ . '/../' . FileCache::RECOMMENDED_DIR;

$container = ContainerProvider::provide_container();

/** @var ContainerCommandLoader $command_loader */

$command_loader = $container->get('console.command_loader');

$console = new Application();
$console->setCommandLoader($command_loader);
$console->run();
