name: test

on:
- push
- pull_request

jobs:
  phpunit:
    name: phpunit
    runs-on: ubuntu-latest
    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        # Maps port 6379 on service container to the host
        - 6379:6379
    strategy:
      matrix:
        php-version:
        - "8.1"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: xdebug
        php-version: "${{ matrix.php-version }}"
        ini-values: memory_limit=-1
        tools: composer:v2
        extensions: redis
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.composer/cache
          vendor
        key: "php-${{ matrix.php-version }}"
        restore-keys: "php-${{ matrix.php-version }}"

    - name: Install dependencies
      run: composer install --no-interaction --no-progress

    - name: Run PHPUnit
      run: make test-coveralls
      env:
        ICANBOOGIE_CLDR_REDIS_HOST: localhost
        ICANBOOGIE_CLDR_REDIS_PORT: 6379
        ICANBOOGIE_CLDR_CHECK_URL: 'yes'

    - name: Upload code coverage
      if: ${{ matrix.php-version == '8.1' }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        composer global require php-coveralls/php-coveralls
        php-coveralls --coverage_clover=build/logs/clover.xml -v
